## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [ ]:
import pandas as pd

In [ ]:
# загружаем датасет
data = pd.read_csv("/content/sample_data/adult.data (1).csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
data.shape

(32561, 15)

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [ ]:
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [ ]:
data[data['sex'] == 'Male']['age'].mean()

39.42272167487685

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [ ]:
len(data[data['native-country'] == 'United-States']) / data.shape[0] * 100

89.540395713108

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [ ]:
right_salary = data[data['salary'] == '>50K']
print(right_salary['age'].mean())
right_salary['age'].std()

44.25082319255547

10.52498362572048

In [ ]:
left_salary = data[data['salary'] == '<=50K']
print(left_salary['age'].mean())
left_salary['age'].std()

36.81180511615294

14.042670012676052

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [ ]:
right_salary['education'].value_counts()

education
Bachelors       1988
HS-grad         1504
Some-college    1210
Masters          858
Prof-school      370
Assoc-voc        318
Doctorate        279
Assoc-acdm       232
10th              60
11th              56
7th-8th           37
12th              31
9th               24
5th-6th           13
1st-4th            5
Name: count, dtype: int64

Нет, не правда. Есть также люди с другим образованием и нужным условием

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [ ]:
data.groupby(['race','sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    111.0  37.459459  13.338109  17.0  27.0  37.0
                   Male      170.0  37.170588  12.124613  18.0  28.0  35.0
Asian-Pac-Islander Female    311.0  35.459807  12.431652  17.0  25.0  34.0
                   Male      617.0  39.465154  13.004588  18.0  30.0  37.0
Black              Female   1393.0  37.762383  12.702281  17.0  28.0  37.0
                   Male     1403.0  37.826800  12.923204  17.0  28.0  36.0
Other              Female    101.0  32.207921  11.887234  17.0  23.0  29.0
                   Male      146.0  34.479452  11.523421  17.0  26.0  32.0
White              Female   7708.0  36.884536  14.384276  17.0  25.0  35.0
                   Male    17152.0  39.616138  13.432167  17.0  29.0  38.0

                            75%   max
race               sex
Amer-Indian-Eskimo Female  47.0  80.0
                   Male    45.0  82.0
Asian-Pac-Islander Female  44.0  75.0
                   Male    47.0  90.0
Black              Female  46.0  90.0
                   Male    46.0  90.0
Other              Female  40.0  74.0
                   Male    41.0  77.0
White              Female  46.0  90.0
                   Male    49.0  90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [ ]:
male_data = data[data['sex']=='Male']

married_types = ['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']

men_married = male_data[male_data['marital-status'].isin(married_types)]
men_sing = male_data[~male_data['marital-status'].isin(married_types)]

print(len(men_married[men_married['salary'] == '>50K']))
len(men_sing[men_sing['salary'] == '>50K'])

5311

630

Среди женатых мужчин зарабатывающих много больше

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [ ]:
max_hours = data['hours-per-week'].max()
print(max_hours)

count_workers = data[data['hours-per-week'] == max_hours]
print(len(count_workers))

len(count_workers[count_workers['salary'] == '>50K'])  / len(count_workers) * 100

99
73

26.027397260273972

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [ ]:
data.groupby(['native-country', 'salary'])['hours-per-week'].mean().unstack()

salary                          <=50K       >50K
native-country
?                           40.105263  46.032258
Cambodia                    41.416667  40.000000
Canada                      37.626667  45.789474
China                       37.274510  38.937500
Columbia                    39.470588  50.000000
Cuba                        38.109375  40.954545
Dominican-Republic          42.379310  47.000000
Ecuador                     37.000000  50.000000
El-Salvador                 35.535714  45.625000
England                     40.157895  44.517241
France                      42.285714  50.818182
Germany                     38.405063  45.756098
Greece                      42.842105  50.625000
Guatemala                   39.500000  40.000000
Haiti                       35.837838  45.333333
Holand-Netherlands          40.000000        NaN
Honduras                    34.727273  60.000000
Hong                        38.300000  45.000000
Hungary                     30.333333  50.000000
India                       38.821429  46.342857
Iran                        42.000000  47.352941
Ireland                     40.166667  48.000000
Italy                       40.447368  45.652174
Jamaica                     38.300000  41.100000
Japan                       40.676471  47.428571
Laos                        40.846154  40.000000
Mexico                      39.961749  47.233333
Nicaragua                   35.862069  37.500000
Outlying-US(Guam-USVI-etc)  45.181818        NaN
Peru                        34.500000  40.000000
Philippines                 38.586777  42.979592
Poland                      38.840909  39.000000
Portugal                    42.206897  41.500000
Puerto-Rico                 38.474747  39.416667
Scotland                    37.500000  40.000000
South                       39.576271  51.533333
Taiwan                      35.607143  46.800000
Thailand                    42.866667  58.333333
Trinadad&Tobago             37.923077  40.000000
United-States               38.806850  45.426111
Vietnam                     36.535714  39.000000
Yugoslavia                  42.000000  49.000000

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [ ]:
def group_age(age):
    if age >= 16 and age <= 35:
        return 'young'
    elif age > 35 and age <= 70:
        return 'adult'
    elif age > 70 and age <= 100:
        return 'retiree'
    else:
        return 'new_group'

data['AgeGroup'] = data['age'].apply(group_age)
data.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,adult
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K,adult
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K,adult
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K,young
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K,adult

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [ ]:
age_group_counts  = data[data['salary'] == '>50K']['AgeGroup'].value_counts()
print(age_group_counts)
age_group_counts.idxmax()

AgeGroup
adult      5378
young      1522
retiree      85
Name: count, dtype: int64

'adult'

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [ ]:
data['occupation'].value_counts()

def filter_func(data):
    if data['age'].mean() <= 40:
        if (data['hours-per-week'] > 5).all():
            return True
    return False

filtered_groups = data.groupby('occupation').filter(filter_func)
filtered_groups['occupation'].value_counts()

occupation
Armed-Forces    9
Name: count, dtype: int64

In [ ]:
data.groupby('occupation')['hours-per-week'].describe()

                    count       mean        std  min   25%   50%   75%   max
occupation
?                  1843.0  31.906131  14.908311  1.0  20.0  36.0  40.0  99.0
Adm-clerical       3770.0  37.558355   9.589833  1.0  37.0  40.0  40.0  80.0
Armed-Forces          9.0  40.666667  14.071247  8.0  40.0  40.0  48.0  60.0
Craft-repair       4099.0  42.304221   9.052038  1.0  40.0  40.0  45.0  99.0
Exec-managerial    4066.0  44.987703  11.109113  1.0  40.0  40.0  50.0  99.0
Farming-fishing     994.0  46.989940  17.320156  2.0  40.0  40.0  60.0  99.0
Handlers-cleaners  1370.0  37.947445  10.580459  2.0  36.0  40.0  40.0  95.0
Machine-op-inspct  2002.0  40.755744   7.592691  1.0  40.0  40.0  40.0  96.0
Other-service      3295.0  34.701669  12.706004  1.0  25.0  40.0  40.0  99.0
Priv-house-serv     149.0  32.885906  16.184548  4.0  22.0  35.0  40.0  99.0
Prof-specialty     4140.0  42.386715  12.536315  1.0  40.0  40.0  50.0  99.0
Protective-serv     649.0  42.870570  12.331777  3.0  40.0  40.0  45.0  99.0
Sales              3650.0  40.781096  13.236410  2.0  35.0  40.0  50.0  99.0
Tech-support        928.0  39.432112  10.583093  3.0  40.0  40.0  40.0  99.0
Transport-moving   1597.0  44.656230  12.721380  5.0  40.0  40.0  50.0  99.0

In [ ]:
data.groupby('occupation')['age'].describe()

                    count       mean        std   min   25%   50%   75%   max
occupation
?                  1843.0  40.882800  20.336350  17.0  21.0  35.0  61.0  90.0
Adm-clerical       3770.0  36.964456  13.362998  17.0  26.0  35.0  46.0  90.0
Armed-Forces          9.0  30.222222   8.089774  23.0  24.0  29.0  34.0  46.0
Craft-repair       4099.0  39.031471  11.606436  17.0  30.0  38.0  47.0  90.0
Exec-managerial    4066.0  42.169208  11.974548  17.0  33.0  41.0  50.0  90.0
Farming-fishing     994.0  41.211268  15.070283  17.0  29.0  39.0  52.0  90.0
Handlers-cleaners  1370.0  32.165693  12.372635  17.0  23.0  29.0  39.0  90.0
Machine-op-inspct  2002.0  37.715285  12.068266  17.0  28.0  36.0  46.0  90.0
Other-service      3295.0  34.949621  14.521508  17.0  22.0  32.0  45.0  90.0
Priv-house-serv     149.0  41.724832  18.633688  17.0  24.0  40.0  57.0  81.0
Prof-specialty     4140.0  40.517633  12.016676  17.0  31.0  40.0  48.0  90.0
Protective-serv     649.0  38.953775  12.822062  17.0  29.0  36.0  47.0  90.0
Sales              3650.0  37.353973  14.186352  17.0  25.0  35.0  47.0  90.0
Tech-support        928.0  37.022629  11.316594  17.0  28.0  36.0  44.0  73.0
Transport-moving   1597.0  40.197871  12.450792  17.0  30.0  39.0  49.0  90.0